### PR TITLE
Default post type example

### PR DESCRIPTION
**Pull request by deadlyhifi**
It took me a few minutes to figure out how to add a taxonomy to the default post type so thought it worthy of being in the readme.

Also corrected Wordpress to WordPress, because [capital P dangit](https://codex.wordpress.org/Function_Reference/capital_P_dangit).

Thanks for making this, very useful.

### CODE REVIEW

**Comment by jjgrainger** [comment]
Nice one!

Though WordPress has a global variable defined as `$post`, so it would be good to change the variable name in the example you've given to avoid any conflict.

Other than that all looks good, and will see about getting it merged soon

:)

**Comment by deadlyhifi** [comment]
Oh yes. Good point well made.

**Comment by jjgrainger** [comment]
Thanks for the PR,

I've not used your work but the changes have been made in the 1.3.2 release.

Thanks :)

**Comment by deadlyhifi** [comment]
Nice one. Thanks. I use this all the time. It makes it all so easy.

**Pull request closed without merging**
